version: "3.8"

services:
  ssh_server:
    build:
      context: ./ssh_server
    container_name: ssh_server
    ports:
      - "2222:22"
    hostname: ssh-server
    networks:
      - reseau_ssh

  ansible_controller:
    build:
      context: ./ansible
    container_name: ansible_controller
    volumes:
      - ./ansible:/ansible
    depends_on:
      - ssh_server
    networks:
      - reseau_ssh
    command: ansible -i /ansible/inventory.ini ssh-server -m ping


networks:
  reseau_ssh:
    driver: bridge
